### ISSUE TITLE
need to support environment-specific hostnames in settings.php

### ISSUE THREAD

**Issue by jsnshrmn** [OULibraries/ansible-role-d7#11]

**Comment by lo5an** [comment]
I think this bug came from the SNI+ngrok issue that Twila and I reported, but I can no-longer duplicate that bug on Windows or MacOS. Possibly we misconfigured things when we were looking at it originally?

**Comment by jsnshrmn** [comment]
No, this is an issue that comes up on servers behind a reverse proxy. The front end passes a hostname header in that is different than the local hostname of the service running on the box.

**Comment by lo5an** [comment]
Roger roger.

**Comment by lo5an** [comment]
I see two entries like

```
## Set public-facing hostname.
$base_url = 'https://rdar.ou.edu';
$cookie_domain = 'rdar.ou.edu';
```

were added to most of the sites on lib-53, and I'm guessing we'll want both of those?

**Comment by jsnshrmn** [comment]
+1

**Comment by jsnshrmn** [comment]
We've tackled parts of this via pr 22, but we still have some way to go.

**Comment by jsnshrmn** [comment]
Closed by https://github.com/OULibraries/ansible-role-d7/pull/32
