### ISSUE TITLE
need to support importing drupal site

### ISSUE THREAD

**Issue by jsnshrmn** [OULibraries/ansible-role-d7#12]
apache config should live in site directory structure and be linked in
need new shell script for import, that will import db, relink config file, and restart apache

**Comment by lo5an** [comment]
Looking at tackling the rest of this issue, what I'm thinking I should do is:
- extract the database import from `d7_sync` to `d7_importdb`
- move the sql file that `d7_sync` creates on the remote host from `$TEMPDIR/drupal_$SITE.sql`   to `$SITE/db/drupal_$SITE.sql`
- make `d7_sync` use `d7_importdb` 
- stop deleting sql file created by `d7_sync` on both remote and localhost

However, that would mean that d7_sync (often running from a remote host) would put its sql file in the same path as d7_dump.  I'm not sure whether that matters. If it does, then sync could dump to ``$SITE/db/drupal_$SITE.sql`, import could take a path,  and everything else basically would work the same. 

I'm also wondering if there's any way to do any validation when importing a dupal sql dump, but I suspect that that's a future enhancement that we don't need until devs start having problems that would solve.

**Comment by jsnshrmn** [comment]
Yes, I'd rather not overwrite the db_dump. Why don't we just have the files named

```
$SITE/db/d7_dump_$SITE.sql
$SITE/db/d7_sync_$SITE.sql
```

or something similar?

**Comment by lo5an** [comment]
I like it.

**Comment by jsnshrmn** [comment]
We've tackled parts of this via pr 22, but we still have some way to go.

**Comment by jsnshrmn** [comment]
We will be able to drop d7_update from d7_sync once d7_import is a part of d7_sync

**Comment by jsnshrmn** [comment]
d7_importdb.sh currently breaks on reinit. If the db user specified in settings.php doesn't already exist, it gets angry. that may be outside the scope of d7_importdb.sh itself, but is an important step of site import.

**Comment by jsnshrmn** [comment]
Closed by https://github.com/OULibraries/ansible-role-d7/pull/28
